t1 = str(input('Escreva a tarefa1: '))
t2 = str(input('Escreva a tarefa2: '))
t3 = str(input('Escreva a tarefa3: '))
t4 = str(input('Escreva a tarefa4: '))
t5 = str(input('Escreva a tarefa5: '))
t6 = str(input('Escreva a tarefa6: '))
t7 = str(input('Escreva a tarefa7: '))
t8 = str(input('Escreva a tarefa8: '))
t9 = str(input('Escreva a tarefa9: '))
t10 = str(input('Escreva a tarefa10: '))

print('Sua tarefas 1:', t1)
print('Sua tarefas 2:' , t2)
print('Sua tarefas 3:' , t3)
print('Sua tarefas 4:' , t4)
print('Sua tarefas 5:' , t5)
print('Sua tarefas 6:' , t6)
print('Sua tarefas 7:' , t7)
print('Sua tarefas 8:' , t8 )
print('Sua tarefas 9: ', t9)
print('Sua tarefas 10:' , t10)